import { Metadata } from "next";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Page",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<PropsWithChildren>)  {
    return (
        <div>
          <span>thinh</span>
          {children}</div>
    )
}